#!/bin/bash
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-nodejs:7}
VERSION=${VERSION-"7"}
S2I_ARGS=${S2I_ARGS:-""}

TEST_APPS=({echo,express,chat,chat-yarn})
VERSION_COMMAND="node --version"

extra_tests() {
  info 'Testing DEV_MODE=true'
  CONTAINER_ARGS='-e DEV_MODE=true' test_application
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/s2i
