#!/bin/bash
source cgroup-limits

set -e
set -o pipefail

# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

yarn() {
  # Since 0.24.6 yarn added a bash intrepeter
  if [ -f "/opt/yarn/bin/yarn.js" ]; then
    node "$NODE_ARGS" /opt/yarn/bin/yarn.js "$@"
  else
    node "$NODE_ARGS" /usr/local/bin/yarn "$@"
  fi
}

npm() {
  node "$NODE_ARGS" /usr/local/bin/npm "$@"
}

# Define the maximum memory limit (total_limit - 32MB)
if [ ${NODE_VERSION:0:1} == "4" ]; then
  # The v8 engine packaged with node4 uses max_old_space_size
  export NODE_ARGS=${NODE_ARGS:-"--max_old_space_size=$((MEMORY_LIMIT-32))"}
else
  export NODE_ARGS=${NODE_ARGS:-"--max-old-space-size=$((MEMORY_LIMIT-32))"}
fi

# Set the debug port and development environment
export NODE_ENV=${NODE_ENV:-"production"}
export NPM_RUN=${NPM_RUN:-"start"}
export DEBUG=${DEBUG:-"FALSE"}
export DEBUG_PORT=${DEBUG_PORT:-"5858"}

# Overwrite NODE_ENV when DEBUG==TRUE
if [ "$DEBUG" == "TRUE" ]; then
  export NODE_ENV=development
fi
