# Add $HOME/node_modules/.bin to the $PATH, allowing user to make npm scripts
# available on the CLI without using npm's --global installation mode
ENV NPM_CONFIG_PREFIX=$HOME/.npm \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm/bin/:$PATH

# Install nodemon
RUN npm install -g nodemon
