#!/bin/bash

NAME="node"
DISPLAY_NAME="Node.js"
REPO="ausnimbus/s2i-nodejs"
TEMPLATES="pre,s2i,template,post"
VARIANT="alpine"
VERSIONS="4,6,7"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
