#!/bin/bash -e

NAME="node"
DISPLAY_NAME="Node.js"
REPO="s2i-nodejs"
TYPE="s2i"
VARIANT="alpine"
VERSIONS="4,6,8"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
